// configs/introLabels.config.js
// Extensive list of customization options for intro animation

export const INTRO_LABELS = [
  // Templates & Structure
  "Template",
  "Page Structure",
  "Site Type",
  "Layout System",
  "Grid Framework",
  "Content Blocks",
  "Page Template",
  "Landing Style",
  "Homepage Layout",
  "Site Architecture",

  // Visual Style
  "Style",
  "Design Style",
  "Visual Theme",
  "Aesthetic",
  "Look & Feel",
  "Design Language",
  "Visual Identity",
  "Brand Style",
  "Art Direction",
  "Design System",

  // Colors
  "Colors",
  "Color Palette",
  "Primary Color",
  "Accent Color",
  "Background Color",
  "Text Color",
  "Color Scheme",
  "Color Mode",
  "Gradient Style",
  "Color Harmony",

  // Typography
  "Typography",
  "Font Family",
  "Heading Font",
  "Body Font",
  "Font Pairing",
  "Type Scale",
  "Line Height",
  "Letter Spacing",
  "Font Weight",
  "Text Style",

  // Layout
  "Layout",
  "Page Layout",
  "Content Layout",
  "Grid Layout",
  "Flexbox Layout",
  "Container Width",
  "Column Layout",
  "Sidebar Layout",
  "Header Layout",
  "Footer Layout",

  // Sections
  "Sections",
  "Hero Section",
  "Features Section",
  "About Section",
  "Services Section",
  "Portfolio Section",
  "Testimonials",
  "Team Section",
  "Pricing Section",
  "FAQ Section",

  // Animation
  "Animation",
  "Animation Style",
  "Scroll Animation",
  "Hover Animation",
  "Page Transitions",
  "Loading Animation",
  "Micro Animations",
  "Motion Design",
  "Entrance Effects",
  "Exit Effects",

  // Images
  "Images",
  "Image Style",
  "Photo Treatment",
  "Image Filters",
  "Image Borders",
  "Image Shadows",
  "Gallery Style",
  "Image Grid",
  "Image Hover",
  "Image Captions",

  // Navigation
  "Navigation Style",
  "Menu Style",
  "Header Style",
  "Nav Position",
  "Mobile Menu",
  "Dropdown Style",
  "Breadcrumbs",
  "Nav Animation",
  "Sticky Header",
  "Menu Icons",

  // Visual Hierarchy
  "Visual Hierarchy",
  "Content Priority",
  "Emphasis Style",
  "Focal Points",
  "Z-Pattern",
  "F-Pattern",
  "Reading Flow",
  "Content Order",
  "Visual Weight",
  "Contrast Ratio",

  // Corners & Shapes
  "Corner Style",
  "Border Radius",
  "Shape Language",
  "Edge Style",
  "Rounded Corners",
  "Sharp Corners",
  "Soft Edges",
  "Geometric Shapes",
  "Organic Shapes",
  "Border Style",

  // Interactions
  "Hover Effects",
  "Click Effects",
  "Focus States",
  "Active States",
  "Touch Feedback",
  "Cursor Style",
  "Interaction Design",
  "Feedback Loops",
  "State Changes",
  "Transitions",

  // Type Scale
  "Type Scale",
  "Font Sizes",
  "Heading Sizes",
  "Body Size",
  "Caption Size",
  "Display Size",
  "Scale Ratio",
  "Responsive Type",
  "Fluid Typography",
  "Type Rhythm",

  // Forms
  "Form Style",
  "Input Style",
  "Button Style",
  "Checkbox Style",
  "Radio Style",
  "Select Style",
  "Form Layout",
  "Validation Style",
  "Error Messages",
  "Success States",

  // Cards
  "Card Style",
  "Card Layout",
  "Card Shadows",
  "Card Borders",
  "Card Hover",
  "Card Content",
  "Card Grid",
  "Card Spacing",
  "Card Animation",
  "Card Variants",

  // Icons
  "Icon Style",
  "Icon Set",
  "Icon Size",
  "Icon Color",
  "Icon Weight",
  "Icon Animation",
  "Icon Placement",
  "Icon Buttons",
  "Social Icons",
  "Feature Icons",

  // Buttons
  "Button Style",
  "Button Size",
  "Button Shape",
  "Button Color",
  "Button Hover",
  "Button States",
  "Button Icons",
  "Button Text",
  "Button Animation",
  "Button Variants",

  // Contact
  "Contact Section",
  "Contact Form",
  "Contact Info",
  "Map Style",
  "Location Display",
  "Phone Display",
  "Email Display",
  "Social Links",
  "Contact CTA",
  "Contact Layout",

  // Copy & Content
  "Copy Length",
  "Content Tone",
  "Writing Style",
  "Headline Style",
  "Subhead Style",
  "Body Copy",
  "Microcopy",
  "CTA Copy",
  "Meta Content",
  "SEO Content",

  // Brand
  "Brand Personality",
  "Brand Voice",
  "Brand Colors",
  "Brand Fonts",
  "Logo Placement",
  "Brand Elements",
  "Visual Branding",
  "Tone of Voice",
  "Brand Guidelines",
  "Brand Assets",

  // Microcopy
  "Micro Copy",
  "Button Labels",
  "Form Labels",
  "Placeholder Text",
  "Helper Text",
  "Tooltip Text",
  "Empty States",
  "Loading Text",
  "Error Copy",
  "Success Copy",

  // Social Proof
  "Social Proof",
  "Testimonials Style",
  "Reviews Display",
  "Rating Style",
  "Client Logos",
  "Case Studies",
  "Trust Badges",
  "Certifications",
  "Awards Display",
  "Statistics",

  // CTA
  "CTA Section",
  "CTA Style",
  "CTA Placement",
  "CTA Color",
  "CTA Size",
  "CTA Animation",
  "CTA Copy",
  "CTA Urgency",
  "CTA Buttons",
  "CTA Banner",
];

export default INTRO_LABELS;
