// Default blob configuration values
export const defaultConfig = {
  // Movement
  floatSpeed: 0.8,
  floatAmplitude: 0.15,
  driftSpeed: 0.5,
  driftAmplitude: 0.1,

  // Rotation
  autoRotateSpeed: 0.15,
  wobbleSpeed: 0.4,
  wobbleAmount: 0.2,
  mouseInfluence: 0.6,

  // Breathing/Scale
  breatheSpeed: 0.7,
  breatheAmount: 0.03,

  // Noise/Distortion
  noiseSpeed: 3.2,
  noiseScale: 2.6,
  distortionBase: 0.14,
  distortionPulse: 0.03,

  // Mouse proximity effect
  mouseProximityEffect: 0.15,

  // Iridescence
  iridescenceIntensity: 1,
  fresnelPower: 3.8,
  iriScale1: 30,
  iriScale2: 14,
  iriSpeed: 2,

  // Material
  baseColorR: 1,
  baseColorG: 1,
  baseColorB: 1,
  envMapIntensity: 0,
  specularIntensity: 0.15,
  specularPower: 8,
  secondarySpecular: 1,
  aoStrength: 0.12,
  brightnessBoost: 1.05,

  // Wall
  wallColorR: 0.81,
  wallColorG: 0.81,
  wallColorB: 0.81,
  wallRoughness: 1,
  wallDistance: 0.5,

  // Main Light
  lightPosX: 0.5,
  lightPosY: 4.5,
  lightPosZ: 8,
  lightIntensity: 3.8,
  lightColorR: 1.0,
  lightColorG: 1.0,
  lightColorB: 1.0,

  // Shadow
  shadowRadius: 24,
  shadowDarkness: 1.0,

  // Ambient Light
  ambientIntensity: 0,
  ambientColorR: 1.0,
  ambientColorG: 1.0,
  ambientColorB: 1.0,

  // Fill Light
  fillIntensity: 2,
  fillPosX: -4,
  fillPosY: 1,
  fillPosZ: 4,

  // Top Light
  topIntensity: 0.8,

  // Camera
  cameraZ: 4.5,
  cameraFOV: 50,

  // Blob Size
  blobScale: 1.2,

  // Time multiplier
  timeScale: 1.0,

  panelCount: 8,
  panelOrbitRadius: 3.8,
  panelRotationSpeed: 0.2,
  panelFloatSpeed: 0.4,
  panelFloatAmplitude: 0.08,
  panelWaveAmplitude: 0.2,
  panelSpacing: 1.1,
  panelTimeScale: 1.0,
  panelMouseInfluence: 0.7,
  panelInteractive: true,
  panelOrbitEnabled: true,

  // Panel Appearance
  panelWidth: 0.08,
  panelHeight: 1.6,
  panelCurvature: 0.3,
  panelOpacity: 0.25,
  panelGlow: 0.1,
  panelHoverGlow: 0.6,

  // Panel Lighting
  panelLightCount: 8,
  panelLightIntensity: 0.2,
};

// Config metadata for UI generation
export const configMeta = {
  motion: {
    label: "Motion",
    fields: {
      floatSpeed: { label: "Float Speed", min: 0, max: 3, step: 0.1 },
      floatAmplitude: {
        label: "Float Amplitude",
        min: 0,
        max: 0.5,
        step: 0.01,
      },
      driftSpeed: { label: "Drift Speed", min: 0, max: 2, step: 0.1 },
      driftAmplitude: {
        label: "Drift Amplitude",
        min: 0,
        max: 0.4,
        step: 0.01,
      },
      autoRotateSpeed: { label: "Auto Rotate", min: 0, max: 1, step: 0.01 },
      wobbleSpeed: { label: "Wobble Speed", min: 0, max: 2, step: 0.1 },
      wobbleAmount: { label: "Wobble Amount", min: 0, max: 1, step: 0.01 },
      mouseInfluence: { label: "Mouse Influence", min: 0, max: 1, step: 0.05 },
      mouseProximityEffect: {
        label: "Proximity Effect",
        min: 0,
        max: 0.5,
        step: 0.01,
      },
      breatheSpeed: { label: "Breathe Speed", min: 0, max: 3, step: 0.1 },
      breatheAmount: {
        label: "Breathe Amount",
        min: 0,
        max: 0.15,
        step: 0.005,
      },
      noiseSpeed: { label: "Noise Speed", min: 0, max: 6, step: 0.1 },
      noiseScale: { label: "Noise Scale", min: 0.5, max: 6, step: 0.1 },
      distortionBase: {
        label: "Distortion Base",
        min: 0,
        max: 0.4,
        step: 0.01,
      },
      distortionPulse: {
        label: "Distortion Pulse",
        min: 0,
        max: 0.15,
        step: 0.005,
      },
      timeScale: { label: "Time Scale", min: 0, max: 3, step: 0.1 },
    },
  },
  material: {
    label: "Material",
    fields: {
      baseColorR: { label: "Base Red", min: 0, max: 1, step: 0.01 },
      baseColorG: { label: "Base Green", min: 0, max: 1, step: 0.01 },
      baseColorB: { label: "Base Blue", min: 0, max: 1, step: 0.01 },
      envMapIntensity: {
        label: "Env Map Intensity",
        min: 0,
        max: 1,
        step: 0.05,
      },
      fresnelPower: { label: "Fresnel Power", min: 0.5, max: 6, step: 0.1 },
      specularIntensity: {
        label: "Specular Intensity",
        min: 0,
        max: 1,
        step: 0.05,
      },
      specularPower: { label: "Specular Power", min: 8, max: 128, step: 4 },
      secondarySpecular: {
        label: "Secondary Specular",
        min: 0,
        max: 1,
        step: 0.05,
      },
      aoStrength: { label: "AO Strength", min: 0, max: 0.5, step: 0.01 },
      brightnessBoost: { label: "Brightness", min: 0.5, max: 2, step: 0.05 },
      blobScale: { label: "Blob Scale", min: 0.5, max: 2, step: 0.05 },
    },
  },
  iridescence: {
    label: "Iridescence",
    fields: {
      iridescenceIntensity: { label: "Intensity", min: 0, max: 2, step: 0.05 },
      iriScale1: { label: "Pattern Scale 1", min: 1, max: 50, step: 0.5 },
      iriScale2: { label: "Pattern Scale 2", min: 1, max: 50, step: 0.5 },
      iriSpeed: { label: "Animation Speed", min: 0, max: 5, step: 0.05 },
    },
  },
  lighting: {
    label: "Lighting",
    fields: {
      lightIntensity: { label: "Main Intensity", min: 0, max: 5, step: 0.1 },
      lightPosX: { label: "Main Pos X", min: -10, max: 10, step: 0.5 },
      lightPosY: { label: "Main Pos Y", min: -10, max: 10, step: 0.5 },
      lightPosZ: { label: "Main Pos Z", min: 0, max: 15, step: 0.5 },
      lightColorR: { label: "Light Red", min: 0, max: 1, step: 0.01 },
      lightColorG: { label: "Light Green", min: 0, max: 1, step: 0.01 },
      lightColorB: { label: "Light Blue", min: 0, max: 1, step: 0.01 },
      shadowRadius: { label: "Shadow Blur", min: 0, max: 30, step: 1 },
      shadowDarkness: { label: "Shadow Darkness", min: 0, max: 1, step: 0.05 },
      ambientIntensity: {
        label: "Ambient Intensity",
        min: 0,
        max: 2,
        step: 0.1,
      },
      ambientColorR: { label: "Ambient Red", min: 0, max: 1, step: 0.01 },
      ambientColorG: { label: "Ambient Green", min: 0, max: 1, step: 0.01 },
      ambientColorB: { label: "Ambient Blue", min: 0, max: 1, step: 0.01 },
      fillIntensity: { label: "Fill Intensity", min: 0, max: 3, step: 0.1 },
      fillPosX: { label: "Fill Pos X", min: -10, max: 10, step: 0.5 },
      fillPosY: { label: "Fill Pos Y", min: -10, max: 10, step: 0.5 },
      fillPosZ: { label: "Fill Pos Z", min: -10, max: 10, step: 0.5 },
      topIntensity: { label: "Top Intensity", min: 0, max: 2, step: 0.1 },
    },
  },
  scene: {
    label: "Scene",
    fields: {
      wallColorR: { label: "Wall Red", min: 0, max: 1, step: 0.01 },
      wallColorG: { label: "Wall Green", min: 0, max: 1, step: 0.01 },
      wallColorB: { label: "Wall Blue", min: 0, max: 1, step: 0.01 },
      wallRoughness: { label: "Wall Roughness", min: 0, max: 1, step: 0.05 },
      wallDistance: { label: "Wall Distance", min: 0.5, max: 5, step: 0.1 },
      cameraZ: { label: "Camera Distance", min: 3, max: 12, step: 0.5 },
      cameraFOV: { label: "Camera FOV", min: 20, max: 90, step: 5 },
    },
  },
  panels: {
    label: "Panels",
    fields: {
      panelCount: { label: "Panel Count", min: 0, max: 16, step: 1 },
      panelOrbitRadius: { label: "Orbit Radius", min: 2, max: 6, step: 0.1 },
      panelRotationSpeed: {
        label: "Rotation Speed",
        min: 0,
        max: 2,
        step: 0.05,
      },
      panelFloatSpeed: { label: "Float Speed", min: 0, max: 2, step: 0.05 },
      panelFloatAmplitude: {
        label: "Float Amplitude",
        min: 0,
        max: 0.5,
        step: 0.01,
      },
      panelWaveAmplitude: {
        label: "Wave Amplitude",
        min: 0,
        max: 1,
        step: 0.05,
      },
      panelSpacing: { label: "Spacing", min: 0.5, max: 2, step: 0.1 },
      panelTimeScale: { label: "Time Scale", min: 0, max: 3, step: 0.1 },
      panelMouseInfluence: {
        label: "Mouse Influence",
        min: 0,
        max: 2,
        step: 0.05,
      },
      panelWidth: { label: "Panel Width", min: 0.01, max: 0.3, step: 0.01 },
      panelHeight: { label: "Panel Height", min: 0.5, max: 3, step: 0.1 },
      panelCurvature: { label: "Curvature", min: 0, max: 1, step: 0.05 },
      panelOpacity: { label: "Opacity", min: 0, max: 1, step: 0.01 },
      panelGlow: { label: "Glow", min: 0, max: 1, step: 0.05 },
      panelHoverGlow: { label: "Hover Glow", min: 0, max: 2, step: 0.05 },
      panelLightCount: { label: "Light Count", min: 0, max: 16, step: 1 },
      panelLightIntensity: {
        label: "Light Intensity",
        min: 0,
        max: 1,
        step: 0.05,
      },
    },
  },
};

// Blob material and animation presets
export const presets = {
  default: {
    label: "Default",
    config: {
      floatSpeed: 0.8,
      floatAmplitude: 0.15,
      driftSpeed: 0.5,
      driftAmplitude: 0.1,
      autoRotateSpeed: 0.15,
      wobbleSpeed: 0.4,
      wobbleAmount: 0.2,
      mouseInfluence: 0.6,
      mouseProximityEffect: 0.15,
      breatheSpeed: 0.7,
      breatheAmount: 0.03,
      noiseSpeed: 3.2,
      noiseScale: 2.6,
      distortionBase: 0.14,
      distortionPulse: 0.03,
      timeScale: 1.0,
      iridescenceIntensity: 1,
      fresnelPower: 3.8,
      baseColorR: 1,
      baseColorG: 1,
      baseColorB: 1,
      envMapIntensity: 0,
      specularIntensity: 0.15,
      specularPower: 8,
      secondarySpecular: 1,
      aoStrength: 0.12,
      brightnessBoost: 1.05,
      iriScale1: 30,
      iriScale2: 14,
      iriSpeed: 2,
      wallColorR: 0.81,
      wallColorG: 0.81,
      wallColorB: 0.81,
      wallRoughness: 1,
      wallDistance: 0.5,
      lightPosX: 0.5,
      lightPosY: 4.5,
      lightPosZ: 8,
      lightIntensity: 3.8,
      lightColorR: 1,
      lightColorG: 1,
      lightColorB: 1,
      shadowRadius: 24,
      shadowDarkness: 1,
      ambientIntensity: 0,
      ambientColorR: 1,
      ambientColorG: 1,
      ambientColorB: 1,
      fillIntensity: 2,
      fillPosX: -4,
      fillPosY: 1,
      fillPosZ: 4,
      topIntensity: 0.8,
      cameraZ: 4.5,
      cameraFOV: 50,
      blobScale: 1.2,
      panelCount: 8,
      panelOrbitRadius: 3.8,
      panelRotationSpeed: 0.2,
      panelFloatSpeed: 0.4,
      panelFloatAmplitude: 0.08,
      panelWaveAmplitude: 0.2,
      panelSpacing: 1.1,
      panelMouseInfluence: 0.7,
      panelWidth: 0.08,
      panelHeight: 1.6,
      panelCurvature: 0.3,
      panelOpacity: 0.25,
      panelGlow: 0.1,
      panelHoverGlow: 0.6,
      panelLightCount: 8,
      panelLightIntensity: 0.2,
    },
  },

  chrome: {
    label: "Chrome",
    config: {
      floatSpeed: 0.6,
      floatAmplitude: 0.1,
      driftSpeed: 0.4,
      driftAmplitude: 0.08,
      autoRotateSpeed: 0.12,
      wobbleSpeed: 0.35,
      wobbleAmount: 0.18,
      mouseInfluence: 0.55,
      mouseProximityEffect: 0.12,
      breatheSpeed: 0.6,
      breatheAmount: 0.025,
      noiseSpeed: 2.8,
      noiseScale: 2.4,
      distortionBase: 0.12,
      distortionPulse: 0.025,
      timeScale: 1.0,
      iridescenceIntensity: 0.1,
      fresnelPower: 1.2,
      baseColorR: 0.9,
      baseColorG: 0.91,
      baseColorB: 0.92,
      envMapIntensity: 0.85,
      specularIntensity: 0.7,
      specularPower: 80,
      secondarySpecular: 0.4,
      aoStrength: 0.1,
      brightnessBoost: 1.2,
      iriScale1: 10,
      iriScale2: 15,
      iriSpeed: 0.3,
      wallColorR: 0.88,
      wallColorG: 0.89,
      wallColorB: 0.9,
      wallRoughness: 0.95,
      wallDistance: 1.2,
      lightPosX: 2,
      lightPosY: 3,
      lightPosZ: 6,
      lightIntensity: 2.0,
      lightColorR: 1,
      lightColorG: 1,
      lightColorB: 1,
      shadowRadius: 15,
      shadowDarkness: 1,
      ambientIntensity: 0.5,
      ambientColorR: 1,
      ambientColorG: 1,
      ambientColorB: 1,
      fillIntensity: 0.7,
      fillPosX: -4,
      fillPosY: 1,
      fillPosZ: 4,
      topIntensity: 0.9,
      cameraZ: 5.5,
      cameraFOV: 40,
      blobScale: 1,
      panelCount: 8,
      panelOrbitRadius: 3.8,
      panelRotationSpeed: 0.2,
      panelFloatSpeed: 0.4,
      panelFloatAmplitude: 0.08,
      panelWaveAmplitude: 0.2,
      panelSpacing: 1.1,
      panelMouseInfluence: 0.7,
      panelWidth: 0.08,
      panelHeight: 1.6,
      panelCurvature: 0.3,
      panelOpacity: 0.25,
      panelGlow: 0.1,
      panelHoverGlow: 0.6,
      panelLightCount: 8,
      panelLightIntensity: 0.2,
    },
  },

  oilSlick: {
    label: "Oil Slick",
    config: {
      floatSpeed: 0.5,
      floatAmplitude: 0.1,
      driftSpeed: 0.3,
      driftAmplitude: 0.08,
      autoRotateSpeed: 0.2,
      wobbleSpeed: 0.3,
      wobbleAmount: 0.15,
      mouseInfluence: 0.5,
      mouseProximityEffect: 0.1,
      breatheSpeed: 0.5,
      breatheAmount: 0.02,
      noiseSpeed: 2.0,
      noiseScale: 2.0,
      distortionBase: 0.1,
      distortionPulse: 0.02,
      timeScale: 1.0,
      iridescenceIntensity: 0.95,
      fresnelPower: 1.5,
      baseColorR: 0.2,
      baseColorG: 0.2,
      baseColorB: 0.22,
      envMapIntensity: 0.6,
      specularIntensity: 0.4,
      specularPower: 48,
      secondarySpecular: 0.2,
      aoStrength: 0.2,
      brightnessBoost: 1.0,
      iriScale1: 8,
      iriScale2: 12,
      iriSpeed: 0.4,
      wallColorR: 0.15,
      wallColorG: 0.15,
      wallColorB: 0.17,
      wallRoughness: 0.95,
      wallDistance: 1.3,
      lightPosX: 2,
      lightPosY: 3,
      lightPosZ: 6,
      lightIntensity: 2.2,
      lightColorR: 1,
      lightColorG: 0.98,
      lightColorB: 0.95,
      shadowRadius: 20,
      shadowDarkness: 1,
      ambientIntensity: 0.3,
      ambientColorR: 0.9,
      ambientColorG: 0.9,
      ambientColorB: 1,
      fillIntensity: 0.5,
      fillPosX: -4,
      fillPosY: 1,
      fillPosZ: 4,
      topIntensity: 0.6,
      cameraZ: 5.5,
      cameraFOV: 40,
      blobScale: 1,
      panelCount: 8,
      panelOrbitRadius: 3.8,
      panelRotationSpeed: 0.2,
      panelFloatSpeed: 0.4,
      panelFloatAmplitude: 0.08,
      panelWaveAmplitude: 0.2,
      panelSpacing: 1.1,
      panelMouseInfluence: 0.7,
      panelWidth: 0.08,
      panelHeight: 1.6,
      panelCurvature: 0.3,
      panelOpacity: 0.25,
      panelGlow: 0.1,
      panelHoverGlow: 0.6,
      panelLightCount: 8,
      panelLightIntensity: 0.2,
    },
  },

  mercury: {
    label: "Mercury",
    config: {
      floatSpeed: 1.0,
      floatAmplitude: 0.12,
      driftSpeed: 0.8,
      driftAmplitude: 0.1,
      autoRotateSpeed: 0.1,
      wobbleSpeed: 0.6,
      wobbleAmount: 0.25,
      mouseInfluence: 0.7,
      mouseProximityEffect: 0.2,
      breatheSpeed: 0.9,
      breatheAmount: 0.04,
      noiseSpeed: 3.5,
      noiseScale: 2.8,
      distortionBase: 0.18,
      distortionPulse: 0.04,
      timeScale: 1.2,
      iridescenceIntensity: 0.5,
      fresnelPower: 1.5,
      baseColorR: 0.75,
      baseColorG: 0.77,
      baseColorB: 0.8,
      envMapIntensity: 0.75,
      specularIntensity: 0.6,
      specularPower: 56,
      secondarySpecular: 0.35,
      aoStrength: 0.12,
      brightnessBoost: 1.15,
      iriScale1: 12,
      iriScale2: 18,
      iriSpeed: 0.6,
      wallColorR: 0.82,
      wallColorG: 0.84,
      wallColorB: 0.86,
      wallRoughness: 0.85,
      wallDistance: 1.1,
      lightPosX: 1,
      lightPosY: 4,
      lightPosZ: 5,
      lightIntensity: 1.9,
      lightColorR: 1,
      lightColorG: 1,
      lightColorB: 1,
      shadowRadius: 12,
      shadowDarkness: 1,
      ambientIntensity: 0.55,
      ambientColorR: 0.95,
      ambientColorG: 0.97,
      ambientColorB: 1,
      fillIntensity: 0.65,
      fillPosX: -5,
      fillPosY: 0,
      fillPosZ: 3,
      topIntensity: 0.75,
      cameraZ: 5,
      cameraFOV: 42,
      blobScale: 1.05,
    },
  },

  gold: {
    label: "Gold",
    config: {
      floatSpeed: 0.6,
      floatAmplitude: 0.1,
      driftSpeed: 0.4,
      driftAmplitude: 0.08,
      autoRotateSpeed: 0.15,
      wobbleSpeed: 0.4,
      wobbleAmount: 0.18,
      mouseInfluence: 0.5,
      mouseProximityEffect: 0.12,
      breatheSpeed: 0.6,
      breatheAmount: 0.025,
      noiseSpeed: 2.5,
      noiseScale: 2.2,
      distortionBase: 0.11,
      distortionPulse: 0.02,
      timeScale: 1.0,
      iridescenceIntensity: 0.2,
      fresnelPower: 1.8,
      baseColorR: 1.0,
      baseColorG: 0.84,
      baseColorB: 0.0,
      envMapIntensity: 0.65,
      specularIntensity: 0.6,
      specularPower: 72,
      secondarySpecular: 0.3,
      aoStrength: 0.15,
      brightnessBoost: 1.1,
      iriScale1: 10,
      iriScale2: 14,
      iriSpeed: 0.4,
      wallColorR: 0.95,
      wallColorG: 0.92,
      wallColorB: 0.85,
      wallRoughness: 0.9,
      wallDistance: 1.2,
      lightPosX: 3,
      lightPosY: 4,
      lightPosZ: 5,
      lightIntensity: 1.6,
      lightColorR: 1,
      lightColorG: 0.95,
      lightColorB: 0.8,
      shadowRadius: 15,
      shadowDarkness: 1,
      ambientIntensity: 0.5,
      ambientColorR: 1,
      ambientColorG: 0.95,
      ambientColorB: 0.85,
      fillIntensity: 0.5,
      fillPosX: -4,
      fillPosY: 1,
      fillPosZ: 4,
      topIntensity: 0.7,
      cameraZ: 5.5,
      cameraFOV: 40,
      blobScale: 1,
    },
  },

  roseGold: {
    label: "Rose Gold",
    config: {
      floatSpeed: 0.5,
      floatAmplitude: 0.08,
      driftSpeed: 0.35,
      driftAmplitude: 0.06,
      autoRotateSpeed: 0.1,
      wobbleSpeed: 0.3,
      wobbleAmount: 0.12,
      mouseInfluence: 0.45,
      mouseProximityEffect: 0.1,
      breatheSpeed: 0.5,
      breatheAmount: 0.02,
      noiseSpeed: 2.2,
      noiseScale: 2.0,
      distortionBase: 0.09,
      distortionPulse: 0.015,
      timeScale: 0.9,
      iridescenceIntensity: 0.25,
      fresnelPower: 2.0,
      baseColorR: 0.92,
      baseColorG: 0.72,
      baseColorB: 0.68,
      envMapIntensity: 0.6,
      specularIntensity: 0.55,
      specularPower: 64,
      secondarySpecular: 0.25,
      aoStrength: 0.12,
      brightnessBoost: 1.05,
      iriScale1: 10,
      iriScale2: 14,
      iriSpeed: 0.35,
      wallColorR: 0.95,
      wallColorG: 0.9,
      wallColorB: 0.88,
      wallRoughness: 0.92,
      wallDistance: 1.25,
      lightPosX: 2,
      lightPosY: 3,
      lightPosZ: 6,
      lightIntensity: 1.7,
      lightColorR: 1,
      lightColorG: 0.92,
      lightColorB: 0.88,
      shadowRadius: 18,
      shadowDarkness: 1,
      ambientIntensity: 0.55,
      ambientColorR: 1,
      ambientColorG: 0.95,
      ambientColorB: 0.92,
      fillIntensity: 0.55,
      fillPosX: -4,
      fillPosY: 1,
      fillPosZ: 4,
      topIntensity: 0.7,
      cameraZ: 5.5,
      cameraFOV: 40,
      blobScale: 1,
    },
  },

  obsidian: {
    label: "Obsidian",
    config: {
      floatSpeed: 0.4,
      floatAmplitude: 0.06,
      driftSpeed: 0.25,
      driftAmplitude: 0.04,
      autoRotateSpeed: 0.08,
      wobbleSpeed: 0.25,
      wobbleAmount: 0.1,
      mouseInfluence: 0.4,
      mouseProximityEffect: 0.08,
      breatheSpeed: 0.4,
      breatheAmount: 0.015,
      noiseSpeed: 1.8,
      noiseScale: 1.8,
      distortionBase: 0.07,
      distortionPulse: 0.01,
      timeScale: 0.8,
      iridescenceIntensity: 0.15,
      fresnelPower: 2.5,
      baseColorR: 0.08,
      baseColorG: 0.08,
      baseColorB: 0.1,
      envMapIntensity: 0.5,
      specularIntensity: 0.8,
      specularPower: 96,
      secondarySpecular: 0.5,
      aoStrength: 0.05,
      brightnessBoost: 1.0,
      iriScale1: 10,
      iriScale2: 15,
      iriSpeed: 0.3,
      wallColorR: 0.12,
      wallColorG: 0.12,
      wallColorB: 0.14,
      wallRoughness: 0.98,
      wallDistance: 1.3,
      lightPosX: 2,
      lightPosY: 4,
      lightPosZ: 7,
      lightIntensity: 2.5,
      lightColorR: 1,
      lightColorG: 1,
      lightColorB: 1,
      shadowRadius: 20,
      shadowDarkness: 1,
      ambientIntensity: 0.2,
      ambientColorR: 0.9,
      ambientColorG: 0.92,
      ambientColorB: 1,
      fillIntensity: 0.4,
      fillPosX: -5,
      fillPosY: 0,
      fillPosZ: 3,
      topIntensity: 0.5,
      cameraZ: 5.5,
      cameraFOV: 40,
      blobScale: 1,
    },
  },

  holographic: {
    label: "Holographic",
    config: {
      floatSpeed: 0.7,
      floatAmplitude: 0.12,
      driftSpeed: 0.5,
      driftAmplitude: 0.1,
      autoRotateSpeed: 0.25,
      wobbleSpeed: 0.5,
      wobbleAmount: 0.2,
      mouseInfluence: 0.6,
      mouseProximityEffect: 0.15,
      breatheSpeed: 0.7,
      breatheAmount: 0.03,
      noiseSpeed: 3.0,
      noiseScale: 2.4,
      distortionBase: 0.12,
      distortionPulse: 0.03,
      timeScale: 0.4,
      iridescenceIntensity: 1.0,
      fresnelPower: 1.2,
      baseColorR: 0.85,
      baseColorG: 0.85,
      baseColorB: 0.9,
      envMapIntensity: 0.6,
      specularIntensity: 0.5,
      specularPower: 48,
      secondarySpecular: 0.3,
      aoStrength: 0.1,
      brightnessBoost: 1.15,
      iriScale1: 6,
      iriScale2: 10,
      iriSpeed: 0.7,
      wallColorR: 0.92,
      wallColorG: 0.9,
      wallColorB: 0.95,
      wallRoughness: 0.9,
      wallDistance: 1.2,
      lightPosX: 0,
      lightPosY: 3,
      lightPosZ: 6,
      lightIntensity: 1.8,
      lightColorR: 1,
      lightColorG: 1,
      lightColorB: 1,
      shadowRadius: 15,
      shadowDarkness: 1,
      ambientIntensity: 0.6,
      ambientColorR: 0.95,
      ambientColorG: 0.95,
      ambientColorB: 1,
      fillIntensity: 0.6,
      fillPosX: -4,
      fillPosY: 1,
      fillPosZ: 4,
      topIntensity: 0.8,
      cameraZ: 5.5,
      cameraFOV: 40,
      blobScale: 1,
    },
  },
};

export const presetList = Object.entries(presets).map(([key, value]) => ({
  id: key,
  ...value,
}));
