// utils/tokenCosts.js
// ═══════════════════════════════════════════════════════════════
// SINGLE SOURCE OF TRUTH for all token cost maps.
// Used by:
//   - Client:  tokenCalculator.js (for UI cost preview)
//   - Server:  edge function calculateTokenCost (for billing)
//
// If you add/change an option cost, update it HERE and both
// consumers stay in sync automatically.
// ═══════════════════════════════════════════════════════════════

export const BASE_COST = 12;
export const REFINEMENT_MIN = 5;
export const REFINEMENT_MAX = 20;
export const GENERATION_MIN = 8;
export const GENERATION_MAX = 50;

// Map of selectionKey → { optionValue: cost }
export const COST_MAPS = {
  template: {
    "Landing Page": 0,
    "Marketing Site": 3,
    "Multi Page": 5,
    Portfolio: 3,
    SaaS: 5,
    Blog: 4,
    "E-commerce": 7,
    Documentation: 4,
    "Web App": 6,
  },
  navigation: {
    Standard: 0,
    "Centered Logo": 2,
    Hamburger: 1,
    Sidebar: 3,
    "Mega Menu": 4,
    Floating: 2,
    Transparent: 2,
    Minimal: 0,
    "Bottom Nav": 2,
    Split: 1,
    Tabbed: 2,
    Breadcrumb: 1,
    "Vertical Dots": 2,
    "Command Palette": 3,
    "No Navigation": 0,
  },
  layout: {
    "Vertical Stack": 0,
    "Single Page": 0,
    "Card Grid": 2,
    "Split Screen": 2,
    Asymmetric: 3,
    Centered: 0,
    Editorial: 2,
    Dashboard: 3,
    Masonry: 3,
    "Hero-Focused": 1,
  },
  contentFlow: {
    Linear: 1,
    "Hub & Spoke": 2,
    "Z Pattern": 2,
    "F Pattern": 2,
    "Inverted Pyramid": 2,
    "Story Arc": 2,
    "Problem-Solution": 2,
    "Feature Led": 1,
    "Benefit Led": 1,
  },
  hierarchy: { Strong: 1, Balanced: 0, Flat: 1 },
  density: { Spacious: 1, Balanced: 0, Compact: 2 },
  style: {
    Minimal: 2,
    Modern: 2,
    Elegant: 2,
    Bold: 2,
    Tech: 2,
    Playful: 2,
    Neumorphic: 3,
    Brutalist: 2,
    Editorial: 2,
    Luxury: 3,
  },
  inspiration: {
    "Modern Startup": 2,
    Apple: 3,
    Stripe: 2,
    Editorial: 2,
    Brutalist: 2,
    Neubrutalism: 2,
    Dashboard: 2,
    Playful: 2,
    Futuristic: 2,
    Corporate: 2,
    Monochrome: 2,
    "Surprise Me": 1,
    Notion: 2,
    Figma: 2,
    Linear: 2,
    Framer: 2,
    Dropbox: 2,
    Spotify: 2,
    "Figma Community": 2,
    "Dribbble Shot": 2,
    Awwwards: 3,
    "SaaS B2B": 2,
    Portfolio: 2,
    Ecommerce: 2,
  },
  gradientStyle: {
    None: 0,
    Subtle: 1,
    Background: 2,
    Text: 2,
    Buttons: 2,
    Cards: 2,
    Mesh: 3,
    Radial: 2,
    Conic: 2,
    Animated: 3,
    Aurora: 3,
    Noise: 2,
  },
  backgroundPattern: {
    None: 0,
    Dots: 1,
    Grid: 1,
    Lines: 1,
    Waves: 2,
    Geometric: 3,
    Noise: 2,
    "Gradient Mesh": 3,
    Blobs: 3,
    Topography: 3,
    Circuit: 3,
    Isometric: 3,
    Paper: 2,
    Fabric: 2,
    Marble: 2,
    Abstract: 3,
    "Photo Overlay": 2,
  },
  corners: { Sharp: 0, Subtle: 0, Rounded: 1, Pill: 2, Fluid: 2 },
  shadowStyle: {
    None: 0,
    Subtle: 1,
    Medium: 1,
    Heavy: 2,
    Colored: 2,
    Hard: 2,
    Layered: 2,
    Inset: 2,
    Long: 2,
    Glow: 2,
    Neumorphic: 3,
    Brutalist: 2,
  },
  hoverEffects: {
    None: 0,
    Subtle: 1,
    Scale: 2,
    Lift: 2,
    Glow: 2,
    "Color Shift": 2,
    Underline: 2,
    Fill: 2,
    Tilt: 3,
    Reveal: 2,
    Magnetic: 3,
    Morphing: 3,
  },
  typographyScale: {
    Compact: 1,
    Default: 0,
    Large: 1,
    Dramatic: 2,
    Fluid: 2,
    Modular: 2,
  },
  headingStyle: {
    Simple: 0,
    Bold: 1,
    Light: 1,
    Uppercase: 1,
    Underlined: 2,
    Highlighted: 2,
    Gradient: 2,
    Outlined: 2,
  },
  heroStyle: {
    Centered: 0,
    Split: 2,
    "Full Screen": 2,
    "Video Background": 3,
    Animated: 3,
    Gradient: 2,
    Minimal: 0,
    "Product Showcase": 2,
    Stats: 2,
    Testimonial: 2,
    Interactive: 4,
    Parallax: 3,
    "3D": 4,
    Carousel: 3,
    "Search Focused": 2,
    "Card Stack": 3,
    Asymmetric: 3,
    "Bento Grid": 3,
  },
  buttonStyle: {
    Solid: 0,
    Outline: 1,
    Gradient: 2,
    Pill: 1,
    Sharp: 0,
    Rounded: 1,
    "Icon + Text": 2,
    Animated: 3,
    "3D/Elevated": 2,
    Underline: 1,
    Glow: 2,
    Neubrutalist: 2,
    Glass: 2,
    Split: 2,
    "Loading States": 2,
  },
  cardStyle: {
    Flat: 0,
    Elevated: 1,
    Bordered: 1,
    Glass: 3,
    Gradient: 2,
    Outlined: 1,
    "Hover Lift": 2,
    "Image Heavy": 3,
    Compact: 0,
    Expanded: 2,
    Asymmetric: 2,
    Stacked: 2,
    Neumorphic: 3,
    Brutalist: 2,
    Interactive: 3,
  },
  formStyle: {
    Standard: 0,
    Underline: 1,
    Filled: 1,
    "Floating Label": 2,
    Outlined: 1,
    Minimal: 0,
    Inline: 1,
    Card: 2,
    Stepped: 3,
    Conversational: 3,
    "Inline Validation": 2,
    Large: 1,
    Compact: 1,
    Searchable: 2,
    "Date Picker": 2,
  },
  iconStyle: {
    Line: 0,
    Solid: 0,
    "Duo-tone": 2,
    Outlined: 0,
    Colored: 2,
    Gradient: 2,
    "3D": 3,
    "Hand-drawn": 2,
    Minimal: 0,
    Detailed: 2,
    Animated: 3,
    Emoji: 0,
    "Custom Illustrations": 3,
    Phosphor: 2,
    Heroicons: 2,
    Lucide: 2,
    Feather: 2,
  },
  badgeStyle: {
    Pill: 0,
    Rounded: 1,
    Square: 0,
    Outlined: 1,
    Filled: 1,
    Dot: 0,
    Gradient: 2,
  },
  avatarStyle: {
    Circle: 0,
    Rounded: 0,
    Square: 0,
    Initials: 1,
    Bordered: 1,
    Stacked: 2,
    "With Status": 2,
  },
  tabStyle: {
    Underline: 0,
    Pill: 1,
    Boxed: 1,
    Button: 1,
    Minimal: 0,
    Vertical: 2,
  },
  accordionStyle: {
    Simple: 0,
    Bordered: 1,
    Card: 2,
    Flush: 0,
    Icon: 1,
    Animated: 2,
  },
  carouselStyle: {
    None: 0,
    Simple: 2,
    Dots: 2,
    Thumbnails: 3,
    "Center Mode": 2,
    "Auto Play": 2,
    Fade: 2,
    "Multi Item": 2,
  },
  notificationStyle: {
    Toast: 2,
    Banner: 1,
    Inline: 0,
    Modal: 2,
    "Slide In": 2,
    Floating: 2,
  },
  progressStyle: {
    Bar: 1,
    Circle: 2,
    Steps: 2,
    Dots: 1,
    Number: 0,
    Percentage: 1,
  },
  tableStyle: {
    Simple: 0,
    Striped: 1,
    Bordered: 1,
    Borderless: 0,
    Cards: 2,
    Compact: 1,
    Sortable: 2,
  },
  listStyle: {
    Standard: 0,
    Check: 1,
    Arrow: 1,
    Number: 0,
    Icon: 2,
    Card: 2,
    Timeline: 3,
  },
  emptyStates: {
    Simple: 0,
    Illustrated: 2,
    Actionable: 1,
    Minimal: 0,
    Animated: 2,
  },
  testimonialStyle: {
    Cards: 1,
    Carousel: 2,
    Grid: 2,
    "Single Featured": 1,
    Masonry: 3,
    Video: 3,
    "Tweet Style": 2,
    "With Logos": 3,
    Marquee: 2,
  },
  pricingStyle: {
    Cards: 1,
    Table: 1,
    Comparison: 2,
    Toggle: 2,
    Tiered: 2,
    Highlighted: 2,
    Minimal: 0,
  },
  statsStyle: {
    Simple: 0,
    Cards: 1,
    Counters: 2,
    Progress: 2,
    Charts: 3,
    Icons: 1,
    Grid: 1,
  },
  teamStyle: {
    Grid: 1,
    Carousel: 2,
    Featured: 2,
    "Hover Reveal": 2,
    "Social Links": 2,
    Minimal: 0,
  },
  faqStyle: {
    Accordion: 1,
    Cards: 2,
    "Two Column": 2,
    Categorized: 2,
    Search: 2,
    Minimal: 1,
  },
  contactStyle: {
    "Form Only": 1,
    "Form + Info": 2,
    Split: 2,
    "Map + Form": 2,
    Calendly: 3,
    Cards: 2,
    Minimal: 0,
  },
  footerStyle: {
    Simple: 0,
    Minimal: 0,
    Standard: 1,
    Fat: 2,
    Mega: 2,
    CTA: 3,
    Newsletter: 3,
    Dark: 1,
  },
  ctaSectionStyle: {
    Centered: 0,
    Split: 2,
    "Full Width": 2,
    Card: 2,
    Gradient: 2,
    "Image Background": 2,
    Floating: 2,
    Newsletter: 2,
  },
  animation: {
    None: 0,
    Minimal: 1,
    Subtle: 2,
    Moderate: 3,
    Expressive: 4,
    Immersive: 5,
    "Performance-First": 1,
  },
  interaction: {
    Static: 0,
    Interactive: 2,
    "App-Like": 3,
  },
  scrollBehavior: {
    Standard: 0,
    Smooth: 1,
    Snap: 2,
    Parallax: 3,
    Reveal: 2,
    Progress: 2,
    Sticky: 2,
  },
  loadingStyle: {
    None: 0,
    Spinner: 1,
    Skeleton: 2,
    "Progress Bar": 2,
    Dots: 1,
    Pulse: 2,
  },
  spacingScale: {
    Tight: 1,
    Default: 0,
    Relaxed: 1,
    Dramatic: 2,
  },
  dividerStyle: {
    None: 0,
    Line: 0,
    Wave: 2,
    Angle: 2,
    Curve: 2,
    Mountain: 2,
    "Gradient Fade": 2,
    "Color Block": 2,
    Zigzag: 2,
    "Torn Paper": 3,
    Dots: 1,
    Space: 0,
  },
  borderWidth: {
    None: 0,
    Hairline: 0,
    Thin: 0,
    Medium: 1,
    Thick: 1,
    Heavy: 2,
  },
  images: {
    Photography: 1,
    Stock: 1,
    "Product Screenshots": 2,
    Illustrations: 2,
    Abstract: 3,
    "3D Graphics": 3,
    "AI Generated": 3,
    "Icons Only": 1,
    "Text Only": 0,
  },
  mediaHandling: {
    Standard: 0,
    "Lazy Load": 2,
    "Blur Up": 2,
    Lightbox: 2,
    Masonry: 2,
    "Video Modal": 2,
    "Responsive Images": 3,
  },
  codeBlockStyle: {
    None: 0,
    Simple: 0,
    Highlighted: 2,
    Dark: 1,
    Light: 1,
    "Line Numbers": 2,
    "Copy Button": 2,
    Terminal: 2,
  },
  framework: {
    "Vanilla CSS": 0,
    "Tailwind Classes": 3,
    "Tailwind + Extracted Components": 4,
    "CSS Modules": 3,
    "BEM CSS": 2,
    "Design Tokens": 3,
  },
  accessibility: { Basic: 0, Standard: 1, Enhanced: 2 },
  seoLevel: { Basic: 0, Standard: 1, Advanced: 2 },
  performanceLevel: { Standard: 0, Optimized: 2, "Ultra Light": 2 },
  mobileMenu: {
    "Hamburger Slide": 0,
    "Full Screen": 2,
    "Bottom Sheet": 2,
    "Bottom Nav": 2,
    Dropdown: 1,
  },
  darkModeToggle: { None: 0, Header: 2, Footer: 2, System: 2 },
  cookieBanner: {
    None: 0,
    Simple: 1,
    "Bottom Bar": 2,
    Corner: 2,
    Minimal: 1,
  },
  socialSharing: {
    None: 0,
    Buttons: 2,
    Links: 1,
    Follow: 2,
    "Open Graph": 2,
  },
  errorPageStyle: {
    Simple: 0,
    Illustrated: 2,
    Animated: 3,
    Playful: 2,
    Minimal: 0,
    Search: 2,
  },
  creativity: { Conservative: 0, Balanced: 0, Experimental: 2 },
  tone: {
    Professional: 1,
    Friendly: 1,
    Authoritative: 1,
    Conversational: 1,
    Inspirational: 2,
    Direct: 1,
  },
  copyLength: { Minimal: 0, Medium: 1, Detailed: 3 },
  cta: { Subtle: 1, Standard: 1, Urgent: 2 },
  goal: {
    "Lead Generation": 1,
    Sales: 2,
    Bookings: 2,
    "Email Signup": 1,
    "Brand Awareness": 1,
    Information: 1,
  },
  industry: {
    Technology: 1,
    SaaS: 1,
    Healthcare: 2,
    Finance: 2,
    "Real Estate": 1,
    Education: 1,
    "E-commerce": 2,
    Agency: 1,
    Marketing: 1,
    "Food & Beverage": 1,
    "Fitness & Wellness": 1,
    Creative: 1,
    Nonprofit: 1,
    Legal: 2,
    Construction: 1,
    Hospitality: 1,
    Manufacturing: 1,
  },
  audience: {
    "General Consumers": 1,
    "B2B Buyers": 1,
    Developers: 2,
    Founders: 1,
    Executives: 2,
    "Enterprise Buyers": 2,
    SMBs: 1,
    Creatives: 1,
    Students: 1,
    Educators: 1,
    Recruiters: 1,
    Agencies: 1,
    "Young Adults": 1,
    "Non-Technical": 1,
  },
  socialProof: {
    None: 0,
    Testimonials: 1,
    Logos: 1,
    Stats: 1,
    Reviews: 2,
  },
  brandPersonality: {
    Professional: 1,
    Friendly: 1,
    Bold: 1,
    Playful: 2,
    Sophisticated: 2,
    Innovative: 2,
    Trustworthy: 1,
    Energetic: 2,
    Calm: 1,
    Warm: 1,
  },
  microCopy: {
    Formal: 1,
    Casual: 1,
    Minimal: 0,
    Helpful: 1,
    Playful: 2,
    Technical: 1,
  },
  responsiveApproach: {
    "Mobile First": 0,
    "Desktop First": 0,
    Fluid: 1,
  },
  emojis: {
    Use: 1,
    "Don't Use": 0,
  },
};

// Keys where cost is conditional on the value being set (use `if (selections.key)`)
// vs always looked up. These are the "content & brand" options that may be unset.
export const CONDITIONAL_KEYS = [
  "inspiration",
  "tone",
  "copyLength",
  "cta",
  "goal",
  "industry",
  "audience",
  "socialProof",
  "brandPersonality",
  "microCopy",
  "responsiveApproach",
  "emojis",
];

// Human-readable labels for breakdown display
export const BREAKDOWN_LABELS = {
  base: "Base generation",
  promptComplexity: "Prompt detail",
  template: "Template type",
  navigation: "Navigation style",
  layout: "Layout type",
  sections: "Extra sections",
  contentFlow: "Content flow",
  hierarchy: "Visual hierarchy",
  density: "Content density",
  style: "Design style",
  inspiration: "Design inspiration",
  customColors: "Custom colors",
  darkMode: "Dark mode",
  gradientStyle: "Gradient usage",
  backgroundPattern: "Background pattern",
  corners: "Corner style",
  shadowStyle: "Shadow style",
  hoverEffects: "Hover effects",
  typographyScale: "Type scale",
  headingStyle: "Heading style",
  heroStyle: "Hero style",
  buttonStyle: "Button style",
  cardStyle: "Card style",
  formStyle: "Form style",
  iconStyle: "Icon style",
  badgeStyle: "Badge style",
  avatarStyle: "Avatar style",
  tabStyle: "Tab style",
  accordionStyle: "Accordion style",
  carouselStyle: "Carousel style",
  notificationStyle: "Notification style",
  progressStyle: "Progress style",
  tableStyle: "Table style",
  listStyle: "List style",
  emptyStates: "Empty states",
  testimonialStyle: "Testimonial style",
  pricingStyle: "Pricing style",
  statsStyle: "Stats display",
  teamStyle: "Team section",
  faqStyle: "FAQ style",
  contactStyle: "Contact style",
  footerStyle: "Footer style",
  ctaSectionStyle: "CTA section",
  animation: "Animations",
  interaction: "Interactivity",
  scrollBehavior: "Scroll behavior",
  loadingStyle: "Loading states",
  spacingScale: "Spacing scale",
  dividerStyle: "Section dividers",
  borderWidth: "Border width",
  images: "Image style",
  mediaHandling: "Media handling",
  codeBlockStyle: "Code blocks",
  framework: "CSS framework",
  accessibility: "Accessibility",
  seoLevel: "SEO focus",
  performanceLevel: "Performance",
  mobileMenu: "Mobile menu",
  darkModeToggle: "Dark mode toggle",
  cookieBanner: "Cookie banner",
  socialSharing: "Social sharing",
  stickyElements: "Sticky UI",
  errorPageStyle: "Error pages",
  creativity: "AI creativity",
  tone: "Tone of voice",
  copyLength: "Copy length",
  cta: "CTA approach",
  goal: "Primary goal",
  industry: "Industry",
  audience: "Target audience",
  socialProof: "Social proof",
  brandPersonality: "Brand personality",
  microCopy: "Micro copy",
  responsiveApproach: "Responsive approach",
  emojis: "Emojis",
};
